name: yaru_example
description: Demonstrates Yaru theming
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.5.0"

dependencies:
  flutter:
    sdk: flutter
  handy_window: ^0.1.6
  yaru:
    path: ../
  yaru_colors: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
