name: yaru
version: 1.2.2

description: Ubuntu Yaru Style - Distinct look and feel of the Ubuntu Desktop

homepage: https://github.com/ubuntu/yaru.dart
issue_tracker: https://github.com/ubuntu/yaru.dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  gtk: ^2.0.0
  platform: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/yaru/src/text/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: packages/yaru/src/text/fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/yaru/src/text/fonts/Ubuntu-R.ttf
          weight: 400
        - asset: packages/yaru/src/text/fonts/Ubuntu-RI.ttf
          weight: 400
          style: italic
        - asset: packages/yaru/src/text/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: packages/yaru/src/text/fonts/Ubuntu-MI.ttf
          weight: 500
          style: italic
        - asset: packages/yaru/src/text/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: packages/yaru/src/text/fonts/Ubuntu-BI.ttf
          weight: 700
          style: italic
